# Generated by Django 3.2.5 on 2021-10-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, verbose_name='Category Name')),
                ('categoryBrand', models.CharField(max_length=100, verbose_name='Category Brand')),
                ('Categorydescription', models.TextField(verbose_name='Description')),
                ('totalPost', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Post')),
                ('totalMessage', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Message')),
            ],
        ),
    ]
