# Generated by Django 3.2.5 on 2021-08-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='message_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='post_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
