# Generated by Django 3.2.5 on 2021-08-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210819_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='post_count',
        ),
        migrations.AlterField(
            model_name='category',
            name='totalMessage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Message'),
        ),
        migrations.AlterField(
            model_name='category',
            name='totalPost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Post'),
        ),
    ]
