# Generated by Django 3.2.5 on 2021-10-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210819_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryBrand',
            field=models.CharField(default=1, max_length=100, verbose_name='Category Brand'),
            preserve_default=False,
        ),
    ]
