# Generated by Django 3.2.5 on 2021-10-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_contactus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='content',
            field=models.TextField(max_length=600),
        ),
    ]
