# Generated by Django 3.2.5 on 2021-09-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userranks_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userranks',
            name='rank_image',
        ),
    ]
