# Generated by Django 3.2.5 on 2021-09-08 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_notifications_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
