# Generated by Django 3.2.5 on 2021-10-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notifications_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_message',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Message'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_post',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Post'),
        ),
    ]
