# Generated by Django 3.2.5 on 2021-10-15 10:15

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20211015_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=froala_editor.fields.FroalaField(null=True, verbose_name='Signature'),
        ),
    ]
