# Generated by Django 3.2.5 on 2021-08-12 23:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='post',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Linked Post'),
        ),
    ]
