# Generated by Django 3.2.5 on 2021-08-12 23:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0002_alter_usermessages_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userposts.userposts', verbose_name='Linked Post'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='postMessages',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Message'),
        ),
    ]
