# Generated by Django 3.2.5 on 2021-08-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0003_auto_20210813_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='last_message',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
