# Generated by Django 3.2.5 on 2021-08-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0006_alter_userposts_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='last_message',
        ),
    ]
