# Generated by Django 3.2.5 on 2021-08-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0007_remove_userposts_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='last_message',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
