# Generated by Django 3.2.5 on 2021-08-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0010_alter_userposts_last_message_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='answer_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Answer Count'),
        ),
    ]
