# Generated by Django 3.2.5 on 2021-08-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0011_userposts_answer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='answer_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Answer Count'),
        ),
    ]
