# Generated by Django 3.2.5 on 2021-08-19 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userposts', '0012_alter_userposts_answer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='like_post',
            field=models.ManyToManyField(related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
