# Generated by Django 3.2.5 on 2021-08-22 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userposts', '0013_userposts_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='like_message',
            field=models.ManyToManyField(related_name='like_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
