# Generated by Django 3.2.5 on 2021-08-23 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userposts', '0014_usermessages_like_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='total_like',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Like'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='like_message',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='like_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
