# Generated by Django 3.2.5 on 2021-08-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0015_auto_20210823_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='total_message',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Message'),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='total_post',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Post'),
        ),
    ]
