# Generated by Django 3.2.5 on 2021-08-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0016_auto_20210824_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='total_message',
        ),
        migrations.RemoveField(
            model_name='usermessages',
            name='total_post',
        ),
    ]
