# Generated by Django 3.2.5 on 2021-08-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0017_auto_20210824_0145'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessages',
            table='UserMessages',
        ),
    ]
