# Generated by Django 3.2.5 on 2021-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0018_alter_usermessages_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='postContent',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
    ]
