# Generated by Django 3.2.5 on 2021-08-26 22:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0020_alter_userposts_postcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='postContent',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Content'),
        ),
    ]
