# Generated by Django 3.2.5 on 2021-08-28 00:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0021_alter_userposts_postcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='postContent',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content'),
        ),
    ]
