# Generated by Django 3.2.5 on 2021-08-28 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userposts', '0023_alter_usermessages_postmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='like_message',
            field=models.ManyToManyField(blank=True, related_name='like_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
