# Generated by Django 3.2.5 on 2021-09-05 21:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userposts', '0025_userposts_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Reply Messsage')),
                ('reply_date', models.DateTimeField(auto_now_add=True, verbose_name='Reply Date')),
                ('related_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='userposts.usermessages')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyUsername', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
