# Generated by Django 3.2.5 on 2021-09-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0026_replymessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymessages',
            name='related_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='userposts.userposts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replymessages',
            name='related_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_message', to='userposts.usermessages'),
        ),
    ]
