# Generated by Django 3.2.5 on 2021-09-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0027_auto_20210906_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userposts.usermessages'),
        ),
        migrations.AlterField(
            model_name='replymessages',
            name='reply_message',
            field=models.TextField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
