# Generated by Django 3.2.5 on 2021-09-07 14:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0028_auto_20210906_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replymessages',
            name='related_post',
        ),
        migrations.AlterField(
            model_name='replymessages',
            name='reply_message',
            field=ckeditor.fields.RichTextField(blank=True, max_length=150),
        ),
    ]
