# Generated by Django 3.2.5 on 2021-09-17 13:27

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0030_remove_replymessages_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replymessages',
            name='reply_message',
            field=froala_editor.fields.FroalaField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='postMessages',
            field=froala_editor.fields.FroalaField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='postContent',
            field=froala_editor.fields.FroalaField(null=True, verbose_name='Content'),
        ),
    ]
