# Generated by Django 3.2.5 on 2021-10-08 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0031_auto_20210917_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyMessages',
        ),
    ]
