# Generated by Django 3.2.5 on 2021-10-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0033_alter_usermessages_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userposts.usermessages'),
        ),
    ]
