# Generated by Django 3.2.5 on 2021-10-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0034_alter_usermessages_replies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessages',
            table=None,
        ),
    ]
