# Generated by Django 3.2.5 on 2021-10-16 00:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0036_alter_userposts_postcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='postMessages',
            field=tinymce.models.HTMLField(null=True, verbose_name='Messages'),
        ),
    ]
